stages:
- prepare-test
- prepare
- build
- test
- deploy
cache:
  paths:
  - bin/
before_script:
- export PATH=$PATH:/usr/local/go/bin

aghanim-build:
  stage: build
  before_script:
  - mkdir bin
  script:
  - go mod tidy
  - go build cmd/web/gin.go
  - mv gin bin
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: false
  retry: 2
  when: on_success

aghanim-deploy:
  stage: deploy
  script:
  - ./bin/gin &
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: false
  retry: 2
  when: on_success
