stages:
- prepare-test
- prepare
- build
- test
- deploy
cache:
  paths:
  - bin/

aghanim-prepare-test:
  stage: prepare-test
  script:
  - mkdir bin
  - go version
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: true

aghanim-prepare:
  stage: prepare
  script:
  - export PATH=$PATH:/usr/local/go/bin
  allow_failure: false
  only:
  - master
  tags:
  - go
  - shell
  when: on_failure

aghanim-build:
  stage: build
  script:
  - go mod tidy
  - go build cmd/web/gin.go
  after_script:
  - mv gin bin
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: false
  retry: 2
  when: on_success

aghanim-deploy:
  stage: deploy
  script:
  - nohub ./bin/gin &
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: false
  retry: 2
  when: on_success
