stages:
- build
- test
- deploy
cache:
  paths:
    - bin/

aghanim-build:
  stage: build
  script:
  - go mod tidy
  - go build cmd/web/gin.go bin/
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: false

aghanim-deploy:
  stage: deploy
  script:
  - ./gin
  only:
  - master
  tags:
  - go
  - shell
  allow_failure: false
